### ISSUE TITLE
RVM installation instructions are faulty

### ISSUE THREAD

**Issue by ovizii** [wpscanteam/wpscan#968]
This step doesn't work as the directories do not exist: 
`source ~/.rvm/scripts/rvm`

this step doesn't work as it seems rvm isn't in the path:
`rvm install 2.3.1` 
so I used the full path:
`/usr/local/rvm/bin/rvm install 2.3.1`

the next step gives me the following output:
`/usr/local/rvm/bin/rvm use 2.3.1 --default`

=> `RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.`

running a test:
`/usr/local/rvm/rubies/ruby-2.3.1/bin/ruby wpscan.rb -u http://mydomain.tld/ -e -r --batch
[ERROR] cannot load such file -- bundler/setup`

This all happened when I updated wpscan from 2.9 to 2.9.2

any hints?

**Comment by ovizii** [comment]
oh, and I only went through those instructions because the DEbian instructions ended up with:
`Ruby >= 2.1.9 required to run wpscan (You have 2.1.5)`
on Debian Jessie

**Comment by ethicalhack3r** [comment]
Thanks for the heads up! As you'll know OSs and their packages are constantly changing so it is difficult for us to keep on top of the installation instructions.

I'll download Debian when I have some spare time and check our instructions, and update them where needed. Thanks again!

**Comment by ovizii** [comment]
Cool, thanks for picking this up. Would love to be able to run this on Debian again. Please update this if anything new comes out of you looking into Debian again.

**Comment by FireFart** [comment]
I changed the readme to include this link. Thanks @ovizii

**Comment by DeeJaVu** [comment]
so how do we install rvm on centos ? source ~/.rvm/scripts/rvm does not exist

**Comment by FireFart** [comment]
@DeeJaVu https://rvm.io/rvm/install
